(() => {
  'use strict';
  const $ = (s, r=document) => r.querySelector(s);
  const $$ = (s, r=document) => [...r.querySelectorAll(s)];
  const providers = [
    {id:'mwamba',initials:'MW',name:'Mwamba Water Works',category:'Plumbing & water repair',model:'Mobile provider',area:'Kabwata + Chilenje service area',reply:'Usually replies within 35 minutes',checks:[['Identity','Current','current'],['Phone','Current','current'],['Plumbing qualification','Current','current'],['Operating location','Checked','current'],['Field visit','Not checked','muted']]},
    {id:'zedspark',initials:'ZS',name:'ZedSpark Electrical Studio',category:'Electrical repair & services',model:'Fixed premises',area:'Customer-facing workshop · Chilenje',reply:'Open today until 17:30',checks:[['Representative identity','Current','current'],['Business registration','Current','current'],['Electrical qualification','Expiring soon','attention'],['Customer-facing premises','Current','current']]},
    {id:'kafue',initials:'KA',name:'Kafue Road Auto Care',category:'Motor-vehicle mechanics',model:'Hybrid provider',area:'Workshop + roadside service · Kabwata',reply:'Next workshop slot tomorrow',checks:[['Representative identity','Current','current'],['Workshop location','Current','current'],['Experience evidence','Reviewed','current'],['Formal qualification','Not supplied','muted']]},
    {id:'brightfix',initials:'BF',name:'BrightFix Appliance Lab',category:'Appliance & electronics repair',model:'Fixed premises',area:'Drop-off counter · pilot area',reply:'Diagnostics slots available today',checks:[['Representative identity','Action required','attention'],['Phone','Current','current'],['Customer-facing premises','Current','current'],['Repair qualification','Under review','attention']]}
  ];
  const nav={customer:[['discover','Discover','⌖'],['saved','Saved','♡'],['enquiries','Enquiries','✉'],['account','Account','●']],provider:[['overview','Overview','⌂'],['evidence','Evidence','▣'],['enquiries','Enquiries','✉'],['account','Account','●']]};
  const state={mode:localStorage.getItem('direkt-mode')||'customer',route:'',provider:providers[0],install:null,theme:localStorage.getItem('direkt-theme')||'light'};
  const esc=v=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
  function route(){const raw=location.hash.replace(/^#\//,'').split('?')[0];const allowed=nav[state.mode].map(x=>x[0]);state.route=allowed.includes(raw)?raw:allowed[0];}
  function go(r){location.hash=`#/${r}`;}
  function navHtml(){return nav[state.mode].map(([id,label,icon])=>`<button class="nav-button ${state.route===id?'is-active':''}" data-route="${id}" ${state.route===id?'aria-current="page"':''}><span class="nav-icon">${icon}</span><span>${label}</span></button>`).join('');}
  function providerCard(p){const chips=p.checks.filter(x=>x[2]==='current').slice(0,3).map(x=>`<span class="chip success">✓ ${esc(x[0])}</span>`).join('');return `<article class="provider-card" tabindex="0" role="button" data-provider="${p.id}"><span class="provider-avatar">${p.initials}</span><div><h3>${esc(p.name)}</h3><p class="provider-meta">${esc(p.category)} · ${esc(p.model)}<br>${esc(p.area)}</p><div class="provider-badges">${chips}</div></div><span class="provider-action">→</span></article>`;}
  function trustRows(p){return p.checks.map(([name,status,tone])=>`<div class="trust-row"><span class="status-dot ${tone}">${tone==='current'?'✓':tone==='attention'?'!':'—'}</span><div><strong>${esc(name)}</strong><small>${tone==='current'?'A current scoped claim is represented in this synthetic preview.':tone==='attention'?'This check needs attention and must not be shown as current.':'No current public claim is represented.'}</small></div><span class="status-label ${tone}">${esc(status)}</span></div>`).join('');}
  function discover(){return `<div class="stack"><section class="hero"><span class="eyebrow">Verified local services · Zambia</span><h2>Find someone nearby. Understand exactly what was checked.</h2><p>DIREKT separates identity, qualification, business, phone and location checks instead of hiding them behind one generic badge.</p><div class="hero-actions"><button class="primary-button" data-action="browse">Browse providers</button><button class="ghost-button" data-action="trust">How checks work</button></div></section><div class="area-bar"><span class="area-icon">⌖</span><div><strong>Kabwata + Chilenje</strong><span>Manual area selected · precise device location not required</span></div><button class="secondary-button" data-action="area">Change</button></div><section class="section"><div class="section-header"><div><span class="eyebrow">Browse</span><h2>What do you need help with?</h2></div></div><div class="category-grid"><button class="category-card">💧<strong>Plumbing</strong><small>Water repair & installations</small></button><button class="category-card">⚡<strong>Electrical</strong><small>Repair & electrical services</small></button><button class="category-card">🔧<strong>Mechanics</strong><small>Vehicle repair & assistance</small></button><button class="category-card">🔌<strong>Appliance repair</strong><small>Electronics & appliances</small></button></div></section><section class="section" id="providers"><div class="section-header"><div><span class="eyebrow">Synthetic preview data</span><h2>Providers matching this area</h2></div><span class="muted">4 results</span></div><div class="page-grid"><div class="provider-list">${providers.map(providerCard).join('')}</div><aside class="stack"><div class="card card--tint"><span class="eyebrow">Trust is scoped</span><h3>“Checked” is not a guarantee.</h3><p>DIREKT shows the exact check, state and limitation. Payment cannot buy stronger trust.</p></div><div class="card"><span class="eyebrow">Location privacy</span><h3>Mobile ≠ storefront</h3><p class="muted">A provider may serve an area without exposing a private home/base coordinate.</p></div></aside></div></section></div>`;}
  function saved(){return `<section class="section"><div class="section-header"><div><span class="eyebrow">Customer</span><h2>Saved providers</h2></div><span class="muted">2 saved</span></div><div class="provider-list">${providers.slice(0,2).map(providerCard).join('')}</div></section>`;}
  function enquiries(){return `<div class="stack"><section class="section"><div class="section-header"><div><span class="eyebrow">Tracked interactions</span><h2>${state.mode==='customer'?'Your enquiries':'Provider enquiry inbox'}</h2></div><button class="primary-button" data-action="enquiry">New enquiry</button></div><div class="action-list"><button class="action-row" data-action="detail"><span class="action-icon">✉</span><div><strong>Water leak repair · Mwamba Water Works</strong><small>Accepted · contact consent available only after explicit action</small></div><span class="status-label current">Active</span></button><button class="action-row" data-action="detail"><span class="action-icon">✉</span><div><strong>Vehicle diagnostics · Kafue Road Auto Care</strong><small>Closed · eligible review state is interaction-derived</small></div><span class="status-label muted">Closed</span></button></div></section><div class="callout warning"><span>!</span><div><strong>No real contact delivery in this public build</strong><p>WhatsApp/call handoff stays disabled here. The backend model preserves consent, expiry, revocation and audit semantics.</p></div></div></div>`;}
  function account(){return `<div class="page-grid"><section class="card"><span class="eyebrow">Account & access</span><h2>${state.mode==='customer'?'Customer account':'Provider account'}</h2><div class="action-list"><button class="action-row" data-action="auth"><span class="action-icon">☎</span><div><strong>Phone sign-in</strong><small>Firebase phone possession flow is implemented but real participant activation remains gated.</small></div><span>→</span></button><button class="action-row" data-action="support"><span class="action-icon">?</span><div><strong>Help & contact</strong><small>View configured DIREKT domain routes</small></div><span>→</span></button></div></section><aside class="card card--tint"><span class="eyebrow">Environment</span><h3>Synthetic remote review</h3><p>No production signup, private evidence, payment or real participant data is enabled through this PWA.</p></aside></div>`;}
  function overview(){return `<div class="stack"><section class="hero compact"><span class="eyebrow">Provider workspace</span><h2>Mwamba Water Works</h2><p>Manage readiness, evidence status, availability and enquiries without allowing profile edits or payment state to create trust claims.</p><div class="metric-grid"><div class="metric"><strong>4</strong><span>Current checks</span></div><div class="metric"><strong>1</strong><span>Needs attention</span></div><div class="metric"><strong>12</strong><span>Open enquiries</span></div></div></section><div class="page-grid"><section class="card"><div class="section-header"><div><span class="eyebrow">Next actions</span><h2>Readiness checklist</h2></div></div><div class="action-list"><button class="action-row" data-route="evidence"><span class="action-icon">!</span><div><strong>Qualification renewal approaching</strong><small>Review evidence timeline and next action.</small></div><span>→</span></button><button class="action-row" data-action="profile"><span class="action-icon">⌖</span><div><strong>Service area</strong><small>Kabwata + Chilenje · mobile provider</small></div><span>→</span></button></div></section><aside class="card card--tint"><span class="eyebrow">Publication boundary</span><h3>Profile readiness is not verification.</h3><p>Only backend-derived, current scoped claims can become public.</p></aside></div></div>`;}
  function evidence(){return `<div class="stack"><section class="section"><div class="section-header"><div><span class="eyebrow">Private evidence workspace</span><h2>Verification progress</h2></div><button class="primary-button" data-action="upload">Upload preview</button></div><div class="trust-list">${trustRows(providers[0])}</div></section><div class="callout"><span>↻</span><div><strong>Recoverable upload design</strong><p>The real Android/backend path uses one logical upload intent with fresh private sessions per retry. This public PWA cannot upload evidence.</p></div></div></div>`;}
  function profile(p){return `<div class="stack"><button class="text-button" data-action="back">← Back to results</button><div class="page-grid"><section class="stack"><div class="card profile-hero"><div class="provider-avatar large">${p.initials}</div><span class="eyebrow">${esc(p.category)}</span><h2>${esc(p.name)}</h2><p>${esc(p.model)} · ${esc(p.area)}</p><span class="muted">${esc(p.reply)}</span><div class="hero-actions"><button class="primary-button" data-action="enquiry">Send tracked enquiry</button><button class="secondary-button" data-action="save">♡ Save</button></div></div><div class="card"><span class="eyebrow">Check-specific trust</span><h2>What DIREKT checked</h2><div class="trust-list">${trustRows(p)}</div></div></section><aside class="stack"><div class="card card--tint"><span class="eyebrow">Important limitation</span><h3>No blanket “verified” badge</h3><p>Checks do not guarantee workmanship, availability, price or future behaviour.</p></div><div class="card"><span class="eyebrow">Location</span><h3>${esc(p.model)}</h3><p class="muted">${esc(p.area)}</p><p class="muted">Private base coordinates are not exposed or used as public distance claims.</p></div></aside></div></div>`;}
  function statusModal(){return `<div class="modal-body"><span class="eyebrow">Repository-aligned checkpoint</span><h2>What this PWA represents</h2><div class="stack"><div class="callout"><span>✓</span><div><strong>Implemented product domains</strong><p>Discovery, provider workspace, verification/evidence, enquiries/reviews and commercial foundations are represented with synthetic states.</p></div></div><div class="callout warning"><span>!</span><div><strong>Not a production launch</strong><p>Real participant auth, communications, payments, live private evidence and production Maps remain separately gated.</p></div></div><div class="callout"><span>↔</span><div><strong>Canonical architecture</strong><p>Android and PWA are designed for the same REST/OpenAPI backend. This public build intentionally makes no private API calls.</p></div></div></div></div>`;}
  function open(html){$('#modal-content').innerHTML=html; if(!$('#modal').open) $('#modal').showModal();}
  function toast(msg){const n=document.createElement('div');n.className='toast';n.textContent=msg;$('#toast-region').append(n);setTimeout(()=>n.remove(),3000);}
  function render(){route();$('#desktop-nav').innerHTML=navHtml();$('#mobile-nav').innerHTML=navHtml();$('#context-label').textContent=state.mode==='customer'?'Customer mode':'Provider mode';const label=nav[state.mode].find(x=>x[0]===state.route)?.[1]||'DIREKT';$('#page-title').textContent=label;let html=state.mode==='customer'?(state.route==='discover'?discover():state.route==='saved'?saved():state.route==='enquiries'?enquiries():account()):(state.route==='overview'?overview():state.route==='evidence'?evidence():state.route==='enquiries'?enquiries():account());$('#main-content').innerHTML=html;}
  function act(t){const r=t.closest('[data-route]')?.dataset.route;if(r)return go(r);const pid=t.closest('[data-provider]')?.dataset.provider;if(pid){state.provider=providers.find(p=>p.id===pid)||providers[0];$('#page-title').textContent='Provider profile';$('#main-content').innerHTML=profile(state.provider);return;}const a=t.closest('[data-action]')?.dataset.action;if(!a)return;({
    browse:()=>$('#providers')?.scrollIntoView({behavior:'smooth'}),trust:()=>open('<div class="modal-body"><span class="eyebrow">Trust model</span><h2>Specific proof, not a blanket badge</h2><p>Identity, contact, business, qualification, location and field-visit checks stay separate. Each claim has its own state and limitation.</p></div>'),area:()=>open('<div class="modal-body"><span class="eyebrow">Location model</span><h2>Manual area remains first-class</h2><p>Live GPS or Google Maps is not required for this review. Manual area/list fallback protects access and privacy.</p></div>'),enquiry:()=>open('<div class="modal-body"><span class="eyebrow">Synthetic form</span><h2>Create a tracked enquiry</h2><label>What do you need?</label><textarea placeholder="Describe the service needed"></textarea><div class="callout warning"><span>!</span><div><strong>Preview only</strong><p>No data is submitted and no contact details are released.</p></div></div></div>'),detail:()=>open('<div class="modal-body"><span class="eyebrow">Tracked interaction</span><h2>Enquiry lifecycle</h2><p>Created → provider response → explicit contact consent → closure → interaction-derived review eligibility.</p></div>'),save:()=>toast('Saved locally for this preview.'),back:()=>go('discover'),upload:()=>open('<div class="modal-body"><span class="eyebrow">Private evidence boundary</span><h2>Upload preview only</h2><p>Real evidence uploads require protected API authorization and private short-lived storage grants. Public PWA uploads are disabled.</p></div>'),auth:()=>open('<div class="modal-body"><span class="eyebrow">Authentication</span><h2>Firebase phone OTP is implemented but gated</h2><p>Real participant activation requires the approved pilot/legal/configuration gates. This public PWA does not initiate OTP.</p></div>'),support:()=>open('<div class="modal-body"><span class="eyebrow">DIREKT contact routes</span><h2>Domain aliases</h2><p>privacy@direkt.forum<br>support@direkt.forum<br>security@direkt.forum<br>legal@direkt.forum<br>pilot@direkt.forum</p></div>'),profile:()=>toast('Profile/service-area editing remains backend-authorized.'),'open-progress':()=>open(statusModal()),account:()=>go('account'),'toggle-theme':()=>{state.theme=state.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=state.theme;localStorage.setItem('direkt-theme',state.theme);}
  })[a]?.();}
  document.addEventListener('click',e=>act(e.target));document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-provider]')){e.preventDefault();act(e.target);}});
  $$('.mode-button').forEach(b=>b.addEventListener('click',()=>{state.mode=b.dataset.mode;localStorage.setItem('direkt-mode',state.mode);$$('.mode-button').forEach(x=>{const on=x===b;x.classList.toggle('is-active',on);x.setAttribute('aria-pressed',String(on));});go(state.mode==='provider'?'overview':'discover');}));
  window.addEventListener('hashchange',render);window.addEventListener('online',()=>{$('#network-status').textContent='Online';toast('Connection restored.');});window.addEventListener('offline',()=>{$('#network-status').textContent='Offline shell';toast('Offline: cached UI remains available.');});
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.install=e;$('#install-app').hidden=false;});$('#install-app').addEventListener('click',async()=>{if(!state.install)return;state.install.prompt();await state.install.userChoice;state.install=null;$('#install-app').hidden=true;});
  if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
  document.documentElement.dataset.theme=state.theme;if(!navigator.onLine)$('#network-status').textContent='Offline shell';route();render();
})();
